Jobsy/Controllers/PrivacyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Jobsy.Controllers
{
    public class PrivacyController : Controller
    {
        // GET: Privacy
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult PrivacyPolicy()
        {
            return View();
        }

        public ActionResult TermsAndConditions()
        {
            return View();
        }
    }
}

Jobsy/Views/Shared/IndexShared/_IndexNavbar.cshtml
@using System.Security.Claims;
@{
    Layout = null;
   
}
}
@Html.Partial("~/Views/Shared/IndexShared/Loading/Preloading.cshtml")


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
     <link rel="shortcut icon" type="image/png" href="~/Content/img/favicon.png">
    <title>Jobsy</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">
    <!-- MDB -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.css"
          rel="stylesheet" />

    <link href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css" rel="stylesheet">

    <link rel="stylesheet" href="~/Content/Index/style.css" />
</head>
<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
        <!-- Container wrapper -->
        <div class="container">
            <!-- Navbar brand -->
            <a class="navbar-brand me-2" href="@Url.Action("Index", "Index")">
                <img src="~/Content/Index/Logo.svg"
                     height="42"
                     alt=""
                     loading="lazy"
                     style="margin-top: -8px;" />
            </a>

            <!-- Toggle button -->
            <button class="navbar-toggler"
                    type="button"
                    data-mdb-toggle="collapse"
                    data-mdb-target="#navbarButtonsExample"
                    aria-controls="navbarButtonsExample"
                    aria-expanded="false"
                    aria-label="Toggle navigation">
                <i class="fas fa-bars"></i>
            </button>

            <!-- Collapsible wrapper -->
            <div class="collapse navbar-collapse" id="navbarButtonsExample">

                @if (User.Identity.IsAuthenticated)
                {
                    @Html.Partial("~/Views/Shared/IndexShared/NavBarPartial/logged_in.cshtml")
                }
                else
                {
                    @Html.Partial("~/Views/Shared/IndexShared/NavBarPartial/not_logged_in.cshtml")
                }

            </div>
            <!-- Collapsible wrapper -->
        </div>
        <!-- Container wrapper -->
    </nav>
    <!-- Navbar -->

    <div>
        @RenderBody()
    </div>

    <style>
        .border-bottom {
            border-bottom: 1px solid #ffffff33 !important;
        }

        footer {
            color: #ffffffe8;
        }
    </style>

    <!-- Footer -->
    <footer class="text-center text-lg-start">
        <!-- Section: Social media -->
        <section class="p-4 border-bottom" style="">

            <!-- Left -->
            <!-- Right -->
            <div class="d-flex justify-content-center">
                <div class="footer-text">
                    <!-- Facebook -->
                    <a class="btn btn-outline-light btn-floating m-1" href="https://www.facebook.com/" target="_blank" role="button">
                        <i class="fab fa-facebook-f"></i>
                    </a>

                    <!-- Twitter -->
                    <a class="btn btn-outline-light btn-floating m-1" href="https://twitter.com/" target="_blank" role="button">
                        <i class="fab fa-twitter"></i>
                    </a>

                    <!-- Google -->
                    <a class="btn btn-outline-light btn-floating m-1" href="https://www.google.com/" target="_blank" role="button">
                        <i class="fab fa-google"></i>
                    </a>

                    <!-- Instagram -->
                    <a class="btn btn-outline-light btn-floating m-1" href="https://www.instagram.com/" target="_blank"  role="button">
                        <i class="fab fa-instagram"></i>
                    </a>

                    <!-- Linkedin -->
                    <a class="btn btn-outline-light btn-floating m-1" href="https://www.linkedin.com/" target="_blank" role="button">
                        <i class="fab fa-linkedin-in"></i>
                    </a>

                    <!-- Github -->
                    <a class="btn btn-outline-light btn-floating m-1" href="https://github.com/" target="_blank" role="button">
                        <i class="fab fa-github"></i>
                    </a>
                </div>
            </div>

            <!-- Right -->
        </section>
        <!-- Section: Social media -->
        <!-- Section: Links  -->
        <section class="">
            <div class="container text-center text-md-start mt-5">
                <!-- Grid row -->
                <div class="row mt-3">
                    <!-- Grid column -->
                    <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
                        <!-- Content -->
                        <h6 class="text-uppercase fw-bold mb-4">
                            <img src="https://firebasestorage.googleapis.com/v0/b/jobsy-e4cf0.appspot.com/o/resources%2FLogo.svg?alt=media&token=ed56d8b1-3a64-43f8-9e19-23313da73c71" alt="logo" />
                        </h6>
                        <p>
                            Jobsy es un sitio web enfocado en que todos aquellos que busquen oportunidades laborales puedan conectarse con empleadores dispuestos a permitirles demostrar lo que son capaces de hacer.
                        </p>
                    </div>
                    <!-- Grid column -->
                    <!-- Grid column -->
                    <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
                        <!-- Links -->
                        <h6 class="text-uppercase fw-bold mb-4">
                            Páginas
                        </h6>
                        <p>
                            <a href="@Url.Action("Index", "Index")" class="text-reset">Inicio</a>
                        </p>
                        <p>
                            <a href="#!" class="text-reset">¿Cómo funciona?</a>
                        </p>
                        <p>
                            <a href="#!" class="text-reset">Sobre Nosotros</a>
                        </p>
                        <p>
                            <a href="#!" class="text-reset">FAQs</a>
                        </p>
                    </div>
                    <!-- Grid column -->
                    <!-- Grid column -->
                    <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
                        <!-- Links -->
                        <h6 class="text-uppercase fw-bold mb-4">
                            Links
                        </h6>
                        <p>
                            <a href="@Url.Action("PrivacyPolicy", "Privacy")" class="text-reset">Privacidad</a>
                        </p>
                        <p>
                            <a href="@Url.Action("TermsAndConditions", "Privacy")" class="text-reset">Términos y condiciones</a>
                        </p>
                        <p>
                            <a href="#!" class="text-reset">Centro de ayuda</a>
                        </p>
                        <p>
                            <a href="#!" class="text-reset">Reportar un error</a>
                        </p>
                    </div>
                    <!-- Grid column -->
                    <!-- Grid column -->
                    <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
                        <!-- Links -->
                        <h6 class="text-uppercase fw-bold mb-4">
                            Contacto
                        </h6>
                        <p><i class="fas fa-home me-3"></i> Santo Domingo, DN 10117, RD</p>
                        <p>
                            <i class="fas fa-envelope me-3"></i>
                            support@jobsy.com
                        </p>
                        <p><i class="fas fa-phone me-3"></i> +1 808 800 5252</p>
                        <p><i class="fas fa-print me-3"></i> +1 808 800 5252</p>
                    </div>
                    <!-- Grid column -->
                </div>
                <!-- Grid row -->
            </div>
        </section>
        <!-- Section: Links  -->
        <!-- Copyright -->
        <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
            © 2021 Copyright: Hecho con ❤️ por
            <a class="text-reset fw-bold" href=""> Capicúa Software</a>
        </div>
        <!-- Copyright -->
    </footer>
    <!-- Footer -->
    <!-- Footer -->
    <!-- MDB -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.js"></script>

    <!--TIDIO INTEGRATION-->
    <script src="//code.tidio.co/6vjzg8cdqnaigy4dbodpaxw2erlutorc.js" async></script>
</body>
</html>